/** @format */

export const ALL_USERS = 'ALL_USERS';
export const GET_ESTABLISHMENT = 'GET_ESTABLISHMENT';
export const ALL_ESTABLISHMENTS = 'ALL_ESTABLISHMENT';
export const FILTER_BY_SPORT = 'FILTER_BY_SPORT';
export const FILTER_BY_LOCATION = 'FILTER_BY_LOCATION';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const SORT_BY_PRICE = 'SORT_BY_PRICE';
export const SORT_BY_AVAILABILITY = 'SORT_BY_AVAILABILITY';
export const REGISTER = 'REGISTER';
export const LOGIN = 'REGISTER';
export const LOGINGOOGLE = 'REGISTER';
export const EDIT_USER = 'EDIT_USER';
export const EDIT_SUCCESS = 'EDIT_SUCCESS'
export const GET_ESTABLISHMENT_BY_ID = 'GET_ESTABLISHMENT_BY_ID';
export const GET_SITES_BY_ESTAB_ID = 'GET_SITES_BY_ESTAB_ID';
export const SET_ERRORS = 'SET_ERRORS';